controller_manager:
  ros__parameters:
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

forward_position_controller:
  ros__parameters:
    joints:
      - fl_m1_s1
      - fl_m2_s2
      - fl_l4_l3
      - fr_m1_s1
      - fr_m2_s2
      - fr_l4_l3
      - bl_m1_s1
      - bl_m2_s2
      - bl_l4_l3
      - br_m1_s1
      - br_m2_s2
      - br_l4_l3

    interface_name: position