controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

forward_position_controller:
  ros__parameters:
    joints:
      - fl_m1_s1
      - fl_m2_s2
      - fl_l4_l3
      - fr_m1_s1
      - fr_m2_s2
      - fr_l4_l3
      - bl_m1_s1
      - bl_m2_s2
      - bl_l4_l3
      - br_m1_s1
      - br_m2_s2
      - br_l4_l3

    interface_name: position
    # command_interfaces:
    #   - position

    # state_interfaces:
    #   - position
    #   - velocity

    # action_monitor_rate: 30.0

    # allow_partial_joints_goal: false
    # open_loop_control: true
    # constraints:
    #   stopped_velocity_tolerance: 0.01
    #   goal_time: 0.0
    #   joint1:
    #     trajectory: 0.05
    #     goal: 0.03
gz_ros_control:
  ros__parameters:
    hold_joints: false
    position_proportional_gain: 0.22