controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    effort_controller:
      type: forward_command_controller/ForwardCommandController

effort_controller:
  ros__parameters:
    joints:
      - br_m1_s1
      - br_m2_s2
      - br_m3_s3
      - fr_m1_s1
      - fr_m2_s2
      - fr_m3_s3
      - bl_m1_s1
      - bl_m2_s2
      - bl_m3_s3
      - fl_m1_s1
      - fl_m2_s2
      - fl_m3_s3
    interface_name: effort