controller_manager:
  ros__parameters:
    effort_controller:
      type: effort_controllers/JointGroupEffortController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    update_rate: 100  # Hz


effort_controller:
  ros__parameters:
    joints:
      - shaft_joint